before:
  hooks:
    - go get -v -d
    - go get -u github.com/swaggo/swag/cmd/swag
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=1
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
 - binaries:
    - go-via
   image_templates:
    - "docker.io/maxiepax/go-via:latest"
   build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
